install:
	npm ci

start:
	npm start

dev:
	npm run dev

build:
	npm run build

lint:
	npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml .
lint-fix:
	npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml . --fix